services:
  mariadb-service:
    container_name: mariadb-container
    image: "mariadb:latest"
    environment:
      MARIADB_DATABASE: operations_db
      MARIADB_USER: operations
      MARIADB_PASSWORD: secret
      MARIADB_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    expose:
      - "3306"
