spring:
  application:
    name: operations

  datasource:
    url: jdbc:mariadb://localhost:3306/operations_db
    username: operations
    password: secret

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: false
        dialect: org.hibernate.dialect.MariaDBDialect

server:
  servlet:
    context-path: /operations/api

app:
  random-org:
    url: https://www.random.org/strings/

  jwt:
    secret: mySecretKey
    expiration: 86400000

  users:
    default:
      username: admin
      password: P@ssw0rd
      balance: 250.00
