spring:
  application:
    name: operations

  datasource:
    url: jdbc:mariadb://localhost:3306/operations_db
    username: operations
    password: secret

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true
    open-in-view: false

  flyway:
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true

server:
  servlet:
    context-path: /operations/api

app:
  random-org:
    url: https://www.random.org/strings/

  jwt:
    secret: mySecretKeyThatIsLongEnoughForHmacSha256Algorithm
    expiration: 86400000

  users:
    default:
      username: admin@example.com
      password: P@ssw0rd
      balance: 250.00

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
