spring:
  application:
    name: operations

  datasource:
    url: ${DB_URL:jdbc:mariadb://localhost:3306/operations_db}
    username: ${DB_USERNAME:operations}
    password: ${DB_PASSWORD:secret}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        "[format_sql]": true
    open-in-view: false

  flyway:
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true

server:
  servlet:
    context-path: /operations/api

app:
  random-org:
    url: https://www.random.org/strings/

  jwt:
    secret: ${JWT_SECRET:mySecretKeyThatIsLongEnoughForHmacSha256Algorithm}
    expiration: ${JWT_EXPIRATION:86400000} # 24 hours in milliseconds
    refresh-expiration: ${JWT_REFRESH_EXPIRATION:604800000} # 7 days in milliseconds

  cache:
    type: simple
    cache-names:
      - tokenBlacklist

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
