CREATE TABLE operations (
    id CHAR(36) PRIMARY KEY DEFAULT (UUID()),
    type VARCHAR(50) UNIQUE NOT NULL,
    cost DECIMAL(19,2) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE INDEX idx_operations_type ON operations(type);
