name: Release Build and Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: gradle

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build and test
        run: ./gradlew clean test build

      - name: Archive artifact
        uses: actions/upload-artifact@v4
        with:
          name: operations-api-jar
          path: build/libs/*.jar

  deploy:
    needs: build-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    env:
      DB_URL: ${{ secrets.DB_URL }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      JWT_EXPIRATION: ${{ secrets.JWT_EXPIRATION }}
      JWT_REFRESH_EXPIRATION: ${{ secrets.JWT_REFRESH_EXPIRATION }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: operations-api-jar
          path: .

      - name: Select JAR (boot jar, not -plain)
        id: jar
        run: |
          JAR=$(ls *.jar | grep -v 'plain' | head -n1)
          if [ -z "$JAR" ]; then echo "No boot JAR found" && ls -lah && exit 1; fi
          echo "JAR_FILE=$JAR" >> "$GITHUB_OUTPUT"

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Known hosts
        run: ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Ensure remote app directory
        run: ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "sudo mkdir -p /opt/operations-api"

      - name: Copy JAR to EC2
        run: scp "${{ steps.jar.outputs.JAR_FILE }}" ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/opt/operations-api/app.jar

      - name: Copy compose.yaml to EC2 (if present)
        run: |
          if [ -f compose.yaml ]; then
            scp compose.yaml ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/opt/operations-api/compose.yaml
          fi

      - name: Render environment file
        run: |
          cat > operations-api.env <<EOF
          DB_URL=${DB_URL}
          DB_USERNAME=${DB_USERNAME}
          DB_PASSWORD=${DB_PASSWORD}
          JWT_SECRET=${JWT_SECRET}
          JWT_EXPIRATION=${JWT_EXPIRATION}
          JWT_REFRESH_EXPIRATION=${JWT_REFRESH_EXPIRATION}
          EOF

      - name: Upload environment file to EC2
        run: scp operations-api.env ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/tmp/operations-api.env

      - name: Move env file and create/update systemd service
        run: |
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} 'bash -s' <<'REMOTE_CMDS'
          set -e
          sudo mv /tmp/operations-api.env /etc/default/operations-api
          sudo chown root:root /etc/default/operations-api
          sudo chmod 600 /etc/default/operations-api
          sudo tee /etc/systemd/system/operations-api.service >/dev/null <<'EOF'
          [Unit]
          Description=Operations API
          After=network.target

          [Service]
          User=ubuntu
          WorkingDirectory=/opt/operations-api
          EnvironmentFile=/etc/default/operations-api
          ExecStart=/usr/bin/java -jar /opt/operations-api/app.jar
          SuccessExitStatus=143
          Restart=always
          RestartSec=5
          AmbientCapabilities=CAP_NET_BIND_SERVICE
          CapabilityBoundingSet=CAP_NET_BIND_SERVICE

          [Install]
          WantedBy=multi-user.target
          EOF
          sudo systemctl daemon-reload
          sudo systemctl enable operations-api || true
          REMOTE_CMDS

      - name: Restart service
        run: |
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "sudo systemctl restart operations-api && sudo systemctl status --no-pager operations-api | cat"
